apiVersion: apps/v1
kind: Deployment
metadata:
  name: unscan-geth-conf
  namespace: uns
  labels:
    app: unscan-geth-conf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unscan-geth-conf
  template:
    metadata:
      labels:
        app: unscan-geth-conf
    spec:
      containers:
        - name: unscan-geth-conf
          image: cryptociva/unscan-nginx-conf
          imagePullPolicy: Always
          # resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: unscan-geth-conf-service
  namespace: uns
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    app: unscan-geth-conf

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unscan-geth-conf-ingress
  namespace: uns
spec:
  rules:
    - host: testnet.unscan.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unscan-geth-conf-service
                port:
                  number: 8080
  ingressClassName: nginx